name: Deploy to GitHub Pages

# 1. 定义触发工作流的事件：当推送到分支时触发，手动触发
on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    # 任务运行的环境：最新版本的 Ubuntu 虚拟机
    runs-on: ubuntu-latest

    # 3. 任务的具体步骤
    steps:
      # 部署到 GitHub Pages 分支
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/
